### ISSUE TITLE
What version of Meteor Angular is being used?

### ISSUE THREAD

**Issue by 6gsaifulislam** [quanganh206/anguar-meteor-offline-contacts#1]
I was using Ground.db fine until I updated to version 1.2.3 - I just wondered what version you are using?

Please see issue raised on Meteor Angular 

https://github.com/Urigo/angular-meteor/issues/919

**Comment by quanganh206** [comment]
Hi @JohnAReid, sorry for late reply. I use meteor 1.2.1
